### ISSUE TITLE
Create MVC for Package

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/eloader-pkg-admin#10]
<img width="623" alt="screen shot 2016-08-17 at 2 19 10 pm" src="https://cloud.githubusercontent.com/assets/3093850/17753653/9b8d92a4-6485-11e6-80f8-2c545c89535f.png">

**Comment by jgreben** [comment]
<img width="609" alt="screen shot 2016-08-17 at 2 20 30 pm" src="https://cloud.githubusercontent.com/assets/3093850/17753691/c5b2b0d2-6485-11e6-9ed0-0b9ee611b7ba.png">

**Comment by shelleydoljack** [comment]
Package MVC created in branch package-mvc. Tests need to be written in order to do pull request.
