### ISSUE TITLE
Add server name to top of pages

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/eloader-pkg-admin#51]
So that the user knows which server s/he is on (test vs. prod).

**Comment by matthewahmed** [comment]
I think showing the server name is a good idea for all web forms. To avoid confusing non-Systems users I would only include the server name for test servers; no server name means it's production.

**Comment by shelleydoljack** [comment]
Re-created in new repo: https://github.com/sul-dlss/libsys-webforms/issues/573
